import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


# ── Ocean Intel branded page template ──────────────────────────────────────
class OceanIntelDocTemplate(SimpleDocTemplate):
    """Custom doc template that adds Ocean Intel header/footer on every page."""

    def __init__(self, buffer, spill_name="", **kwargs):
        super().__init__(buffer, **kwargs)
        self.spill_name = spill_name

    def handle_pageBegin(self):
        super().handle_pageBegin()
        self._draw_branding()

    def _draw_branding(self):
        canvas = self.canv
        page_w, page_h = letter

        # ── Top branded header bar ──
        canvas.saveState()
        canvas.setFillColor(colors.HexColor("#0f172a"))
        canvas.rect(0, page_h - 22, page_w, 22, fill=1, stroke=0)

        # Left: OCEAN INTEL wordmark
        canvas.setFillColor(colors.HexColor("#14b8a6"))
        canvas.setFont("Helvetica-Bold", 9)
        canvas.drawString(10, page_h - 15, "◈  OCEAN INTEL")

        # Center: subtitle
        canvas.setFillColor(colors.HexColor("#94a3b8"))
        canvas.setFont("Helvetica", 7.5)
        canvas.drawCentredString(page_w / 2, page_h - 15, "Marine Protection Gang  ·  SAR Intelligence Platform")

        # Right: CONFIDENTIAL stamp
        canvas.setFillColor(colors.HexColor("#f43f5e"))
        canvas.setFont("Helvetica-Bold", 7.5)
        canvas.drawRightString(page_w - 10, page_h - 15, "RESTRICTED — OPERATIONAL USE ONLY")
        canvas.restoreState()

        # ── Bottom footer ──
        canvas.saveState()
        canvas.setFillColor(colors.HexColor("#f1f5f9"))
        canvas.rect(0, 0, page_w, 18, fill=1, stroke=0)
        canvas.setStrokeColor(colors.HexColor("#cbd5e1"))
        canvas.setLineWidth(0.5)
        canvas.line(0, 18, page_w, 18)

        canvas.setFillColor(colors.HexColor("#64748b"))
        canvas.setFont("Helvetica", 7)
        ts = datetime.now(timezone.utc).strftime("%d %b %Y  %H:%M UTC")
        canvas.drawString(10, 5, f"Generated by Ocean Intel SAR Intelligence Platform  ·  {ts}  ·  Data: Sentinel-1 SAR / Copernicus PostGIS")
        canvas.drawRightString(page_w - 10, 5, f"Page {canvas.getPageNumber()}  ·  oceanintel.io")
        canvas.restoreState()


def generate_icg_report(spill_data: dict) -> io.BytesIO:
    buffer = io.BytesIO()
    doc = OceanIntelDocTemplate(
        buffer,
        spill_name=spill_data.get('name', ''),
        pagesize=letter,
        rightMargin=36,
        leftMargin=36,
        topMargin=44,       # extra room for top bar
        bottomMargin=30,    # extra room for footer
    )
    elements = []
    styles = getSampleStyleSheet()

    # Base typography styles
    cell_bold   = ParagraphStyle('CellBold',   parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=8, leading=10, textColor=colors.HexColor("#1e293b"))
    cell_normal = ParagraphStyle('CellNormal', parent=styles['Normal'], fontName='Helvetica',      fontSize=8, leading=10, textColor=colors.HexColor("#334155"))
    alert_style = ParagraphStyle('Alert',      parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=9, leading=12, textColor=colors.HexColor("#b91c1c"))

    # ── Ocean Intel data-source attribution row ──
    source_style = ParagraphStyle('Source', parent=styles['Normal'], fontName='Helvetica', fontSize=7.5, leading=10, textColor=colors.HexColor("#64748b"))
    src_row = Table(
        [[Paragraph("Intelligence Source: <b>Ocean Intel SAR Intelligence Platform</b>  ·  Satellite Imagery: <b>Sentinel-1 SAR (ESA Copernicus)</b>  ·  AIS Correlation: <b>MarineTraffic / AISHub</b>  ·  Metocean: <b>Open-Meteo Marine API</b>", source_style)]],
        colWidths=[540]
    )
    src_row.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), colors.HexColor("#f0fdfa")),
        ('BOX',           (0,0), (-1,-1), 0.5, colors.HexColor("#99f6e4")),
        ('TOPPADDING',    (0,0), (-1,-1), 5),
        ('BOTTOMPADDING', (0,0), (-1,-1), 5),
        ('LEFTPADDING',   (0,0), (-1,-1), 8),
        ('RIGHTPADDING',  (0,0), (-1,-1), 8),
    ]))
    elements.append(src_row)
    elements.append(Spacer(1, 10))

    # Dynamically assign regional authority based on EEZ
    eez_name = str(spill_data.get('eez', '')).upper()
    if "INDIA" in eez_name:
        authority = "INDIAN COAST GUARD"
    elif "OMAN" in eez_name:
        authority = "OMAN MARITIME SECURITY AGENCY"
    elif "LIBYA" in eez_name:
        authority = "MEDITERRANEAN MARITIME TASK FORCE"
    elif "US" in eez_name:
        authority = "US COAST GUARD (USCG) INCIDENT COMMAND"
    elif "MALAYSIA" in eez_name:
        authority = "MALAYSIA MARITIME ENFORCEMENT AGENCY (MMEA)"
    elif "UK" in eez_name:
        authority = "UK MARITIME & COASTGUARD AGENCY (MCA)"
    elif "NIGERIA" in eez_name:
        authority = "NIGERIAN MARITIME SAFETY ADMINISTRATION"
    else:
        authority = f"{eez_name} MARITIME SAFETY COMMISSION"

    title_style = ParagraphStyle(
        'Title', parent=styles['Heading1'], fontSize=15, leading=18,
        textColor=colors.HexColor("#0f172a"), spaceAfter=4
    )
    elements.append(Paragraph(f"{authority}: SAR INCIDENT DOSSIER", title_style))
    elements.append(Paragraph(
        f"SURVEILLANCE ID: <b>{spill_data.get('name', 'UNKNOWN')}</b> &bull; STATUS: <b>{spill_data.get('status', 'Confirmed').upper()}</b>",
        styles['Normal']
    ))
    elements.append(Spacer(1, 10))

    # Dark vessel alert if applicable
    is_dark = spill_data.get('vessel', {}).get('is_dark', False)
    if is_dark:
        alert_text = (
            "CRITICAL WARNING: UNIDENTIFIED 'DARK VESSEL' DETECTED<br/>"
            "AIS transponder intentionally unbroadcasted. Target localized exclusively via Sentinel-1 SAR metallic radar backscatter reflection."
        )
        t_alert = Table([[Paragraph(alert_text, alert_style)]], colWidths=[540])
        t_alert.setStyle(TableStyle([
            ('BACKGROUND',    (0,0), (-1,-1), colors.HexColor("#fef2f2")),
            ('BOX',           (0,0), (-1,-1), 1, colors.HexColor("#ef4444")),
            ('TOPPADDING',    (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('LEFTPADDING',   (0,0), (-1,-1), 8),
            ('RIGHTPADDING',  (0,0), (-1,-1), 8),
        ]))
        elements.append(t_alert)
        elements.append(Spacer(1, 10))

    overview = [
        [
            Paragraph("Detection Location", cell_bold), Paragraph(str(spill_data.get('location', '')), cell_normal),
            Paragraph("AI Confidence",       cell_bold), Paragraph(f"{spill_data.get('confidence', 0)}%", cell_normal)
        ],
        [
            Paragraph("Platform",   cell_bold), Paragraph(str(spill_data.get('satellite', '')), cell_normal),
            Paragraph("Orbit Pass", cell_bold), Paragraph(str(spill_data.get('orbit_pass', '')), cell_normal)
        ],
        [
            Paragraph("Jurisdiction",   cell_bold), Paragraph(str(spill_data.get('eez', '')), cell_normal),
            Paragraph("SAR Timestamp", cell_bold), Paragraph(str(spill_data.get('date_display', '')), cell_normal)
        ],
        [
            Paragraph("Surface Area",  cell_bold), Paragraph(f"{spill_data.get('area_km2', 0)} sq km", cell_normal),
            Paragraph("Spill Length",  cell_bold), Paragraph(f"{spill_data.get('length_km', 0)} km", cell_normal)
        ],
        [
            Paragraph("Slick Morphology", cell_bold), Paragraph(str(spill_data.get('spill_type', 'Trailing Wake')), cell_normal),
            Paragraph("Center Lat/Lon",   cell_bold), Paragraph(f"{spill_data.get('center', [0,0])[1]:.3f}°N, {spill_data.get('center', [0,0])[0]:.3f}°E", cell_normal)
        ]
    ]
    t1 = Table(overview, colWidths=[110, 160, 100, 170])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f8fafc")),
        ('GRID',       (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING',    (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    elements.append(t1)
    elements.append(Spacer(1, 14))

    # Primary vessel
    elements.append(Paragraph("PRIMARY CORRELATED VESSEL DETAILS", styles['Heading3']))
    v = spill_data.get('vessel', {})
    v_len = f"{v.get('length_m')} m" if v.get('length_m') else "Unknown"
    vessel_info = [
        [
            Paragraph("Vessel Name", cell_bold), Paragraph(str(v.get('name', 'Unknown')), cell_normal),
            Paragraph("MMSI",        cell_bold), Paragraph(str(v.get('mmsi', 'Unknown')), cell_normal)
        ],
        [
            Paragraph("Vessel Type", cell_bold), Paragraph(str(v.get('type', 'Unknown')), cell_normal),
            Paragraph("IMO Number",  cell_bold), Paragraph(str(v.get('imo',  'Unknown')), cell_normal)
        ],
        [
            Paragraph("Flag State",   cell_bold), Paragraph(str(v.get('flag', 'Unknown')), cell_normal),
            Paragraph("LOA (Length)", cell_bold), Paragraph(v_len, cell_normal)
        ]
    ]
    t2 = Table(vessel_info, colWidths=[110, 160, 100, 170])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#f1f5f9")),
        ('GRID',       (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('TOPPADDING',    (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    elements.append(t2)
    elements.append(Spacer(1, 12))

    # Secondary vessel
    sec_v = spill_data.get('secondary_vessel')
    if sec_v:
        elements.append(Paragraph("SECONDARY COINCIDENT VESSEL (CORRIDOR / STS PARTNER)", styles['Heading3']))
        s_len = f"{sec_v.get('length_m')} m" if sec_v.get('length_m') else "Unknown"
        sec_info = [
            [
                Paragraph("Vessel Name", cell_bold), Paragraph(str(sec_v.get('name', 'Unknown')), cell_normal),
                Paragraph("MMSI",        cell_bold), Paragraph(str(sec_v.get('mmsi', 'Unknown')), cell_normal)
            ],
            [
                Paragraph("Vessel Type", cell_bold), Paragraph(str(sec_v.get('type', 'Unknown')), cell_normal),
                Paragraph("IMO Number",  cell_bold), Paragraph(str(sec_v.get('imo',  'Unknown')), cell_normal)
            ],
            [
                Paragraph("Flag State",   cell_bold), Paragraph(str(sec_v.get('flag', 'Unknown')), cell_normal),
                Paragraph("LOA (Length)", cell_bold), Paragraph(s_len, cell_normal)
            ]
        ]
        t3 = Table(sec_info, colWidths=[110, 160, 100, 170])
        t3.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#faf5ff")),
            ('GRID',       (0,0), (-1,-1), 0.5, colors.HexColor("#e9d5ff")),
            ('TOPPADDING',    (0,0), (-1,-1), 4),
            ('BOTTOMPADDING', (0,0), (-1,-1), 4),
        ]))
        elements.append(t3)
        elements.append(Spacer(1, 12))

    elements.append(Paragraph("OPERATIONAL ACTION DIRECTIVE", styles['Heading3']))
    if is_dark:
        mandate = (
            f"This discharge footprint has been correlated with an unidentified non-broadcasting radar contact using Sentinel-1 SAR. "
            f"Immediate naval/aerial reconnaissance by {authority} is requested for visual identification, photographic evidence gathering, and intercept."
        )
    else:
        mandate = (
            f"This discharge footprint has been correlated with the aforementioned vessel using Sentinel-1 SAR imagery and historical AIS telemetry. "
            f"Urgent aerial verification, port-state detention upon arrival, and environmental sampling by {authority} is recommended."
        )
    elements.append(Paragraph(mandate, styles['Normal']))
    elements.append(Spacer(1, 20))

    # ── Closing Ocean Intel signature block ──
    sig_style = ParagraphStyle('Sig', parent=styles['Normal'], fontName='Helvetica', fontSize=7.5, leading=11, textColor=colors.HexColor("#475569"))
    sig_bold  = ParagraphStyle('SigB', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=7.5, leading=11, textColor=colors.HexColor("#0f172a"))
    sig_table = Table(
        [[
            Paragraph("<b>Ocean Intel</b><br/>Marine Protection Gang<br/>SAR Intelligence Platform", sig_bold),
            Paragraph(
                "This document has been automatically generated by the Ocean Intel SAR Intelligence Platform "
                "using Sentinel-1 Synthetic Aperture Radar (SAR) imagery processed via the Copernicus PostGIS pipeline. "
                "Data is provided for operational maritime law enforcement purposes only. "
                "Unauthorised redistribution is prohibited.",
                sig_style
            )
        ]],
        colWidths=[130, 410]
    )
    sig_table.setStyle(TableStyle([
        ('BACKGROUND',    (0,0), (-1,-1), colors.HexColor("#f8fafc")),
        ('BOX',           (0,0), (-1,-1), 0.5, colors.HexColor("#94a3b8")),
        ('LINEAFTER',     (0,0), (0,-1),  0.5, colors.HexColor("#94a3b8")),
        ('TOPPADDING',    (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ('LEFTPADDING',   (0,0), (-1,-1), 10),
        ('RIGHTPADDING',  (0,0), (-1,-1), 10),
        ('VALIGN',        (0,0), (-1,-1), 'MIDDLE'),
    ]))
    elements.append(sig_table)

    doc.build(elements)
    buffer.seek(0)
    return buffer